function [simulTime, velTimes, attTimes, omgTimes] = initRatesPID()
    simulTime = 60; % (s)
    
    omgRate = 1000;
    attRate = 250;
    velRate = 50;
    
    omgSamplingTime = 1/omgRate;
    attSamplingTime = 1/attRate;
    velSamplingTime = 1/velRate;
    
    omgTimes = struct( ...
        "dt", omgSamplingTime,...
        "rate", omgRate,...
        "timeSim", simulTime);
    attTimes = struct( ...
        "dt", attSamplingTime,...
        "rate", attRate,...
        "timeSim", simulTime);
    velTimes = struct( ...
        "dt", velSamplingTime,...
        "rate", velRate,...
        "timeSim", simulTime);
end

