function [initCond, initInput, params, simTime] = initSimul()
    initCond = struct(...
        "pos", [0; 0; 10],...
        "vel", [3; 0; 0],...
        "quat", [1; 0; 0; 0],...
        "omg", [0; 0; 0]);

    initThrust = 19.62;     % N
    initMoment = [0; 0; 0]; % Nm
    initInput = [initThrust; initMoment];

    simTime = 60;
    params = struct(...
        "Mass", 2,...
        "armLength", 0.25,...
        "Ixx", 0.021667,...
        "Ixy", 0,...
        "Ixz", 0,...
        "Iyy", 0.021667,...
        "Iyz", 0,...
        "Izz", 0.04);
end

