function pYpVTheta2 = pYpVTheta2(V_phi_1,V_phi_2,V_r_1,V_r_2,V_theta_1,V_theta_2,r_1,r_2)
%pYpVTheta2
%    pYpVTheta2 = pYpVTheta2(V_phi_1,V_phi_2,V_r_1,V_r_2,V_theta_1,V_theta_2,R_1,R_2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-04-29 10:30:23

t2 = V_phi_1.^2;
t3 = V_phi_2.^2;
t4 = V_r_1.^2;
t5 = V_r_2.^2;
t6 = V_theta_1.^2;
t7 = V_theta_2.^2;
t8 = r_2.^2;
t9 = t2+t6;
t10 = t3+t7;
t11 = t4+t9;
t12 = t5+t10;
t13 = sqrt(t9);
t14 = sqrt(t10);
t15 = 1.0./t14;
t16 = 1.0./t11;
t17 = 1.0./t12;
t19 = 1.0./sqrt(t11);
t20 = 1.0./sqrt(t12);
t25 = t11+t12;
t18 = t17.^2;
t21 = t20.^3;
t22 = V_r_1.*r_1.*t16;
t23 = V_r_2.*r_2.*t17;
t26 = r_1.*t13.*t19;
t27 = r_2.*t14.*t20;
t29 = V_theta_2.*r_2.*t15.*t20;
t24 = -t23;
t28 = V_theta_2.*r_2.*t14.*t21;
t34 = t26+t27;
t31 = t22+t24;
t35 = 1.0./t34.^2;
t36 = 1.0./t34.^3;
t32 = t31.^2;
t37 = t35.^2;
t33 = t32.^2;
t39 = V_theta_2.*t32.*t35.*2.0;
t40 = t12.*t32.*t35;
t42 = t25.*t32.*t35;
t41 = t40+1.0;
t43 = t11.*t12.*t33.*t37;
t44 = t42+t43+1.0;
t45 = sqrt(t44);
pYpVTheta2 = t26.*t28.*t45.*-2.0+t26.*t29.*t45.*2.0+t8.*t10.*t17.*(t39+V_theta_2.*t23.*t31.*t35.*4.0+t12.*t32.*t36.*(t28-t29).*2.0)+V_theta_2.*t8.*t17.*t41.*2.0+r_1.^2.*t9.*t16.*(t11.*t32.*t36.*(t28-t29).*2.0+V_r_2.*V_theta_2.*r_2.*t11.*t18.*t31.*t35.*4.0)+(t26.*t27.*(t39+V_theta_2.*t11.*t33.*t37.*2.0+t25.*t32.*t36.*(t28-t29).*2.0+t11.*t12.*t33.*1.0./t34.^5.*(t28-t29).*4.0+V_theta_2.*t11.*t23.*t31.^3.*t37.*8.0+V_r_2.*V_theta_2.*r_2.*t18.*t25.*t31.*t35.*4.0))./t45-V_theta_2.*t8.*t10.*t18.*t41.*2.0;
end
