function pYpVTheta1 = pYpVTheta1(V_phi_1,V_phi_2,V_r_1,V_r_2,V_theta_1,V_theta_2,r_1,r_2)
%pYpVTheta1
%    pYpVTheta1 = pYpVTheta1(V_phi_1,V_phi_2,V_r_1,V_r_2,V_theta_1,V_theta_2,R_1,R_2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-04-29 10:30:22

t2 = V_phi_1.^2;
t3 = V_phi_2.^2;
t4 = V_r_1.^2;
t5 = V_r_2.^2;
t6 = V_theta_1.^2;
t7 = V_theta_2.^2;
t8 = r_1.^2;
t9 = t2+t6;
t10 = t3+t7;
t11 = t4+t9;
t12 = t5+t10;
t13 = sqrt(t9);
t14 = sqrt(t10);
t15 = 1.0./t13;
t16 = 1.0./t11;
t18 = 1.0./t12;
t19 = 1.0./sqrt(t11);
t21 = 1.0./sqrt(t12);
t25 = t11+t12;
t17 = t16.^2;
t20 = t19.^3;
t22 = V_r_1.*r_1.*t16;
t23 = V_r_2.*r_2.*t18;
t26 = r_1.*t13.*t19;
t27 = r_2.*t14.*t21;
t29 = V_theta_1.*r_1.*t15.*t19;
t24 = -t23;
t28 = V_theta_1.*r_1.*t13.*t20;
t34 = t26+t27;
t31 = t22+t24;
t35 = 1.0./t34.^2;
t36 = 1.0./t34.^3;
t32 = t31.^2;
t37 = t35.^2;
t33 = t32.^2;
t39 = V_theta_1.*t32.*t35.*2.0;
t41 = t11.*t32.*t35;
t43 = t25.*t32.*t35;
t42 = t41+1.0;
t44 = t11.*t12.*t33.*t37;
t45 = t43+t44+1.0;
t46 = sqrt(t45);
pYpVTheta1 = t27.*t28.*t46.*-2.0+t27.*t29.*t46.*2.0+t8.*t9.*t16.*(t39-V_theta_1.*t22.*t31.*t35.*4.0+t11.*t32.*t36.*(t28-t29).*2.0)+V_theta_1.*t8.*t16.*t42.*2.0+r_2.^2.*t10.*t18.*(t12.*t32.*t36.*(t28-t29).*2.0-V_r_1.*V_theta_1.*r_1.*t12.*t17.*t31.*t35.*4.0)+(t26.*t27.*(t39+V_theta_1.*t12.*t33.*t37.*2.0+t25.*t32.*t36.*(t28-t29).*2.0+t11.*t12.*t33.*1.0./t34.^5.*(t28-t29).*4.0-V_theta_1.*t12.*t22.*t31.^3.*t37.*8.0-V_r_1.*V_theta_1.*r_1.*t17.*t25.*t31.*t35.*4.0))./t46-V_theta_1.*t8.*t9.*t17.*t42.*2.0;
end
