function cnvntn = simplicationSpheroid(velInfo, relC1Pos, relC2Pos)
    r01 = norm(relC1Pos);
    r02 = norm(relC2Pos);

    U1 = sqrt(velInfo.c1.thetaVel^2 + velInfo.c1.phiVel^2);
    U2 = sqrt(velInfo.c2.thetaVel^2 + velInfo.c2.phiVel^2);
    V1 = sqrt(velInfo.c1.thetaVel^2 + velInfo.c1.phiVel^2 + velInfo.c1.rVel^2);
    V2 = sqrt(velInfo.c2.thetaVel^2 + velInfo.c2.phiVel^2 + velInfo.c2.rVel^2);
    A1 = r01 * U1 / V1;
    A2 = r02 * U2 / V2;
    tau = ((r01 * velInfo.c1.rVel / V1^2 - r02 * velInfo.c2.rVel / V2^2) / (r01 * U1 / V1 + r02 * U2 / V2))^2;
    cnvntn = struct( ...
        "U1", U1,...
        "U2", U2,...
        "V1", V1,...
        "V2", V2,...
        "A1", A1,...
        "A2", A2,...
        "tau", tau);
end

